### PR TITLE
feat: support ! for notifying breaking change

### PR DESCRIPTION
**Pull request by damianopetrungaro**

### CODE REVIEW

**Comment by damianopetrungaro** [comment]
@adrians5j  @Pavel910 any update on this?

**Comment by Pavel910** [comment]
@damianopetrungaro Oh so sorry we missed this 🤦‍♂️ I'm on my phone right now but will review and get back to you later today/tomorrow. Thanks for the nudge 👍

**Review by adrians5j — APPROVED** [review]
Looks good, let's merge!

**Comment by adrians5j** [comment]
Thanks @damianopetrungaro for the fix, much appreciated!

Sorry for the delay too! 🙂

**Comment by adrians5j** [comment]
BTW just update the version of the action to 1.0.5 and you should be good to go.

**Pull request merged**
